language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool
script: xctool -project Example/Example.xcodeproj -scheme Example build test -sdk iphonesimulator
